# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# trigger:
# - dev

pool:
  vmImage: 'ubuntu-18.04'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    sudo add-apt-repository ppa:ubuntugis/ppa
    sudo apt-get update
    sudo apt-get -y install grass-core grass-dev
  displayName: 'Install GRASS'

- script: |
    python -m pip install --upgrade pip
    python -m pip install numpy setuptools cython
  displayName: 'Install dependencies'

- script: |
    cython -3 itzi/swmm/swmm_c.pyx itzi/flow.pyx
    python -m pip install .
  displayName: 'Cythonize, build and install'

- script: |
    pip3 install pandas requests pytest pytest-cov pytest-xdist pytest-azurepipelines
    pytest --cov=itzi --forked -v --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
  displayName: 'pytest'
