name: tests

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    runs-on: ubuntu-24.04
    container: osgeo/grass-gis:releasebranch_8_4-ubuntu
    steps:
    - name: Install dependencies
      run: |
        apt update
        apt install -y ca-certificates clang build-essential libomp-dev nodejs

    - uses: actions/checkout@v5

    - name: Cache downloaded Zenodo test data
      uses: actions/cache@v4
      with:
        path: |
          tests/test_data_temp/Test8A_dataset_2010.zip
          tests/test_data_temp/Test8B_dataset_2010.zip
          tests/test_data_temp/elev_lid792_1m.gtiff
        key: zenodo-data-${{ hashFiles('tests/test_ea8a.py', 'tests/test_ea8b_icechunk.py', 'tests/grass_tests/test_tutorial.py') }}
        restore-keys: |
          zenodo-data-

    - name: Install uv and Python
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        $HOME/.local/bin/uv python install ${{ matrix.python-version }}

    - name: Pytest
      run: |
        $HOME/.local/bin/uv run --all-extras --python ${{ matrix.python-version }} pytest --cov=src --forked --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html tests/

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
